name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  CI-CD:
  
    runs-on: ubuntu-latest

    steps:
    
    ## env setting
    - uses: actions/checkout@v2
    - name: Set env
      run: 
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
  
    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    ## docker build & push to develop
    - name: Docker build & push to dev
      if: contains(github.ref, 'dev')
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} {{ secrets.HOST_DEV }} 
        docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/mozi-server:dev
        docker push ${{ secrets.DOCKER_REPO }}/mozi-server:dev
        
  ## time
  current-time:
    needs: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가

      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
